### ISSUE TITLE
Coding Style Guide

### ISSUE THREAD

**Issue by decipherIO** [tranvnb/course-registration-assisstant#20]
I added an editorconfig file with some basic coding style guides. But I never consulted with you guys about it. And now I have started to work on the project, I'm not very satisfied with the style guide myself. Wanted to get you guys input. this is the current style guide on the editorconfig file

```
root = true

[*]
end_of_line = crlf
insert_final_newline = true

[*.{js,css}]
indent_style = space
indent_size = 2
```

One thing I would like to change is for js files
from:

```
[.js]
indent_style = space
indent_size = 2
```

to

```
[.js]
indent_style = tab
indent_size = 4
```

I would like to get your input on this.

Thanks

**Comment by tranvnb** [comment]
I would prefer indent_size: 2

**Comment by NancyLakhanpal** [comment]
Yeah I agree with @tranvnb

**Comment by decipherIO** [comment]
@NancyLakhanpal and @tranvnb Understood. Is there any other style changes you guys would prefer?

**Comment by NancyLakhanpal** [comment]
I am okay with this.
