### ISSUE TITLE
Color Scheme for the App

### ISSUE THREAD

**Issue by decipherIO** [tranvnb/course-registration-assisstant#21]
@tranvnb Submitted a nice template that we could use for our app:

[Smart Home Template](https://www.invisionapp.com/inside-design/design-resources/smart-home-ui-kit/)

[Home Page Image](https://s3.amazonaws.com/www-inside-design/uploads/2019/02/4.0-Rules-min.png)

We need to pick a color scheme for the app and apply to our header, footer and all other main components of the app.

[Here](https://color.adobe.com/create/color-wheel) is a color scheme tool you can use to try out different colors

What are your suggestions?

**Comment by NancyLakhanpal** [comment]
The following is the design and color scheme to be followed while developing the web application. Try to achieve similar designs for every story.
 
![FirstScreen](https://user-images.githubusercontent.com/76132994/111053108-f684a580-8415-11eb-8ffc-6e79bee108a3.png)

![loginSignup](https://user-images.githubusercontent.com/76132994/111053111-fbe1f000-8415-11eb-8c13-c0dad5ab5acf.png)

This the just the example for colors and kind of design we can have, but the image in the card will be different.
![Dashboard](https://user-images.githubusercontent.com/76132994/111053120-000e0d80-8416-11eb-8831-ef4d8daa25dc.png)

![Create new schedule](https://user-images.githubusercontent.com/76132994/111053125-03a19480-8416-11eb-9fcd-6b4a1d24d36e.png)

![NewTimetable](https://user-images.githubusercontent.com/76132994/111053130-08664880-8416-11eb-8c99-053fd1fa36d1.png)

![search page](https://user-images.githubusercontent.com/76132994/111053131-0b613900-8416-11eb-9608-d8796978f090.png)

![Search page with advanced filters](https://user-images.githubusercontent.com/76132994/111053133-0dc39300-8416-11eb-88da-51f0200fc685.png)

![Complete Timetable](https://user-images.githubusercontent.com/76132994/111053145-22079000-8416-11eb-9c3b-a8978c61288f.png)

**Comment by NancyLakhanpal** [comment]
@tranvnb @MrDecipher  Please review the design.
