### ISSUE TITLE
As a team member, I want to setup the project structure for other member to start working on

### ISSUE THREAD

**Issue by tranvnb** [tranvnb/course-registration-assisstant#3]
>estimate 5

**Comment by decipherIO** [comment]
Is this in regards to set up a development environment for the team to start working on the project? If this is what the issue is on, I am willing to take it on

**Comment by tranvnb** [comment]
Yes, please, but first you need to add estimation for this. I will update the estimation this time. But next time, the estimation number must be approved by  all team member.
Please, I pull the project to your PC first, then add unit tests, containers, components, and other things you think we might use.

**Comment by decipherIO** [comment]
> 
> 
> Yes, please, but first you need to add estimation for this. I will update the estimation this time. But next time, the estimation number must be approved by all team member.
> Please, I pull the project to your PC first, then add unit tests, containers, components, and other things you think we might use.

What is the estimation criteria? Is it by **difficulty** or amount of **time** taken to resolve an issue?

**Comment by tranvnb** [comment]
@MrDecipher : It is the difficulty of the task compare to the smallest task. For example the easiest task is create new react app (using create-react-app only) will be 1 point, then compare to it, your configuration and constructing task is more complex and difficult => should be 2, 3, 5, 8 (Fibonacci numbers) .
