### ISSUE TITLE
As a developer, I want to have the mockup/wireframe of the web page for starting the implementation

### ISSUE THREAD

**Issue by tranvnb** [tranvnb/course-registration-assisstant#4]
> estimate 5

**Comment by tranvnb** [comment]
![3380 wireframe](https://user-images.githubusercontent.com/9379521/105771463-72ce3280-5f15-11eb-8805-3ae2cc9449fa.png)
@MrDecipher , @NancyLakhanpal : please have a look to the wireframe from draw.io. I dont create new branch for this issue because it is a image from outside source code. If you approved, just add a comment under this issue. Then its good to go.

**Comment by NancyLakhanpal** [comment]
@tranvnb Approved from my side.
