### ISSUE TITLE
As a developer, I want to have a header component implemented to use in dashboard page

### ISSUE THREAD

**Issue by tranvnb** [tranvnb/course-registration-assisstant#8]
###Acceptance criteria:

1. Header must have a name of logged in user
2. Must has unit test for the component including content text and snapshot, please refer this [tutorial](https://reactjs.org/docs/testing-recipes.html#snapshot-testing).

> estimate 5

**Comment by tranvnb** [comment]
@NancyLakhanpal any update on this issue?

**Comment by NancyLakhanpal** [comment]
Please review header component @tranvnb @MrDecipher

**Comment by NancyLakhanpal** [comment]
The branch name is feature/issue-8-nla-25
